### ISSUE TITLE
Access blocked

### ISSUE THREAD

**Issue by patirot** [hipudding/teslamate_fix_addrs#10]
INFO:root:checking empty records...
INFO:root:processing drive address (184 left)
ERROR:root:Http request failed by url: https://nominatim.openstreetmap.org/reverse?lat=22.792001&lon=113.931184&format=jsonv2&addressdetails=1&extratags=1&namedetails=1&zoom=18, code: 403, body: <html>
<head>
<title>Access blocked</title>
</head>
<body>
<h1>Access blocked</h1>

<p>You have been blocked because you have violated the
<a href="https://operations.osmfoundation.org/policies/nominatim/">usage policy</a>
of OSM's Nominatim geocoding service. Please be aware that OSM's resources are
limited and shared between many users. The usage policy is there to ensure that
the service remains usable for everybody.</p>

<p>Please review the terms and make sure that your
software adheres to the terms. You should in particular verify that you have set a
<b>custom HTTP referrer or HTTP user agent</b> that identifies your application, and
that you are not overusing the service with massive bulk requests.</p>

<p>If you feel that this block is unjustified or remains after you have adopted
your usage, you may contact the Nominatim system administrator at
nominatim@openstreetmap.org to have this block lifted.</p>
</body>
</head>

**Comment by patirot** [comment]
resolved, using vaild UA 

-ua "Chrome/125.0.0.0"

**Comment by hipudding** [comment]
-ua teslamate/#v1.30.1
也可以更新镜像，默认ua已经设置
