### ISSUE TITLE
地址后面多了一个逗号

### ISSUE THREAD

**Issue by sleepgod** [hipudding/teslamate_fix_addrs#2]
<img width="744" alt="截屏2024-01-24 10 01 46" src="https://github.com/hipudding/teslamate_fix_addrs/assets/3087328/0cb58cc5-c8e3-41f8-94d8-25c4acb38fe5">

**Comment by hipudding** [comment]
感谢使用，这个问题应该是在地址split的时候没有去除最后的逗号，我会尽快修复。建议先使用高德地图做一下地址更新，能暂时 规避这个问题，并且使得地址更加详细。

**Comment by sleepgod** [comment]
感谢回复，我是使用高德地图更新的。
<img width="640" alt="截屏2024-01-24 10 22 11" src="https://github.com/hipudding/teslamate_fix_addrs/assets/3087328/8635d8d8-3539-4375-96bc-96ca8986c74e">

~~~
python3 teslamate_fix_addrs.py -k be2af3487******0643517217d -u teslamate -p ** -H ***.168.5.*** -P 5432 -d teslamate -m 1 -t 10
~~~

**Comment by hipudding** [comment]
用高德地图更新后，按道理说地址就会更新成高德的格式，也就不会有逗号了，好神奇，我看看哈，修复了我会回复issue。

**Comment by hipudding** [comment]
我看了下，这个逗号后面应该要拼接城市名称，看起来是城市名称没有解析出来，方便导出一份数据库备份给我看下么？可以发送到：huafengchun@gmail.com，调试完成后我会删除所有数据

**Comment by sleepgod** [comment]
已发送，请查收。

**Comment by hipudding** [comment]
明白了，因为你在北京市，北京是直辖市，所以”北京”会解析到state中，city就为空了，我修复下，直辖市特殊处理下就好

**Comment by hipudding** [comment]
已修复：[29c9b32](https://github.com/hipudding/teslamate_fix_addrs/commit/29c9b323abea13b517fa7f6c4677cced8c9d4148)
