### ISSUE TITLE
潜在问题需要处理

### ISSUE THREAD

**Issue by hipudding** [hipudding/teslamate_fix_addrs#3]
目前每次loop会返回处理成功的条目，如果条目为0，则sleep一段时间后再次运行。

如果loop中出现错误，for循环会continue，但是还是返回这些数据都处理了，这样会导致频繁处理这条有错误的数据。应当返回正常处理的条目，以跳过无法处理的数据。

处理空数据的时候要考虑如何标记无法解析的数据，不跳过可能会导致一直处理这些错误数据。

另外，env和docker-compose更新下，新增since参数

**Comment by Plyer** [comment]
我看了部分代码，可能理解的不准确，说说我的想法。

空数据查询的时候可以加个 offset，类似分页，循环到末尾就会自动结束了，可以先解决死循环。

标记空数据我有两个想法，一个是直接写 no_data 跟 None 区分开，防止被查询出来，但是不知道这样对 teslamate 展示会不会有影响；二是在数据库中创建一张表保存无法解析的数据，做关联查询。

```py
page_num = 1
def fix_address(session, batch_size, empty_count):
    # get empty records in drives.
    empty_drive_addresses = session\
        .query(Drives)\
        .filter(or_(Drives.start_address_id.is_(None), Drives.end_address_id.is_(None)))\
        .filter(Drives.start_position_id.is_not(None))\
        .filter(Drives.end_position_id.is_not(None))\
        .offset((page_num - 1) * batch_size)\ #分页
        .limit(batch_size)\
        .all()
    page_num += 1
```

**Comment by hipudding** [comment]
> 我看了部分代码，可能理解的不准确，说说我的想法。
> 
> 空数据查询的时候可以加个 offset，类似分页，循环到末尾就会自动结束了，可以先解决死循环。
> 
> 标记空数据我有两个想法，一个是直接写 no_data 跟 None 区分开，防止被查询出来，但是不知道这样对 teslamate 展示会不会有影响；二是在数据库中创建一张表保存无法解析的数据，做关联查询。
> 
> ```python
> page_num = 1
> def fix_address(session, batch_size, empty_count):
>     # get empty records in drives.
>     empty_drive_addresses = session\
>         .query(Drives)\
>         .filter(or_(Drives.start_address_id.is_(None), Drives.end_address_id.is_(None)))\
>         .filter(Drives.start_position_id.is_not(None))\
>         .filter(Drives.end_position_id.is_not(None))\
>         .offset((page_num - 1) * batch_size)\ #分页
>         .limit(batch_size)\
>         .all()
>     page_num += 1
> ```

感谢你的关注！
第一个问题其实是执行错误了但是在计数上没有做处理，这个修改方法是只有处理成功的才增加计数就可以了。（一直懒得改🌚)。不过更好的方法是记录上次一扫描记录的id值，扫过的id不再处理。如果你有时间，可以提PR来修复。

空数据的问题，其实我不太想新增一张表来记录，这个工具尽可能的不侵入teslamate的数据，可以记录到本地文件，或者简单点，直接存到内存里，我觉得空数据的数量应该也不会很多，把空数据的id记下来就好了。

**Comment by hipudding** [comment]
1. 不需要再使用osm更新location
2. amap更新默认从当前时间开始，历史数据传0
3. 启动后修改存储过程和grafana，自动换为amap
