### ISSUE TITLE
必须要有代理才行运行吗

### ISSUE THREAD

**Issue by requestdaye** [hipudding/teslamate_fix_addrs#4]
请问 为什么空的地址填写是使用OSM  更新地址又是用的高德的  空地址不能用高德的接口吗

**Comment by hipudding** [comment]
用OSM更新是为了和官方保持一致，然后高德是根据OSM地址来修改地址。这个开始做成了两个功能，所以没有直接用高德来解析空地址。

**Comment by hipudding** [comment]
teslamate设计的数据库都是基于osm的，里面有osm_id，osm_type，osm_raw等信息，如果直接用高德解析也没问题，但是有可能由于没有这几个osm的数据，导致不可预期的问题。
所以最好的方法就是按teslamate的原始方法先用osm解析，然后用高德仅仅更新其中的一些字段。

**Comment by hipudding** [comment]
如果实在不想用OSM先解析地址，可以试试 amap这个分支。这个分支会将地址算md5，然后存到osm_type这个字段中。所有的osm地址会被删除。使用前请先备份，并且阅读源码理解风险。

**Comment by benson0308** [comment]
teslamate版本 1.33.0

ymal文件：
  teslamate_fix_addrs:
    image: hipudding/teslamate_fix_addrs:latest
    container_name: teslmate_fix_addrs
    restart: unless-stopped
    environment:
    - DB_USER=teslamate
    - DB_PASSWD=123456
    - DB_HOST=database
    - DB_PORT=5432
    - DB_NAME=teslamate
    - BATCH=10
    - HTTP_TIMEOUT=5
    - HTTP_RETRY=5
    - INTERVAL=10
    - MODE=1
    - SINCE=2024-01-24
    - KEY=10964a4f4c3fa641787cf85c*******
    - USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

无法正常显示地点

**Comment by hipudding** [comment]
@benson0308  贴下log看看
