### ISSUE TITLE
teslamate 1.30.1，使用amap mode无法更新位置信息

### ISSUE THREAD

**Issue by BanghuiSun** [hipudding/teslamate_fix_addrs#9]
![2f07e5653edc02664745f79517bce36a](https://github.com/user-attachments/assets/c0378c08-6c5d-4194-81da-1e4ce28808bc)
![b0160d8b9e2a4e1a5ce4d3ed44578512](https://github.com/user-attachments/assets/e71f5529-2c76-407d-8a41-658bc9f8a8cc)

**Comment by hipudding** [comment]
收到，会尽快检查原因

**Comment by odinms** [comment]
我是1.30.1。。 我没遇到任何问题呢。。

**Comment by hipudding** [comment]
已经验证1.30.1，功能正常，可以尝试重启下这个容器

**Comment by BanghuiSun** [comment]
重启容器后恢复正常，谢谢
